### PR TITLE
iOS build 

### PR DESCRIPTION
**Pull request by eins78**
It works! :rocket: 

Steps documented [in README](https://github.com/nimaai/nlr-app/blob/ios/README.md)

Runnning:
screen shot 2015-02-14 at 12 50 17

On Home Screen:
screen shot 2015-02-14 at 12 50 30

### CODE REVIEW

**Comment by eins78** [comment]
I added a `package.json`, for two reasons: it builds without a global install of cordova (otherwise a build-machine could only have one global version of it), and it adds some scripts to build in one command.
Only `"cordova": "cordova"` is really needed, it "proxies" all the commands to the locally installed cordova package (needs a recent (>=2.0.0) version of `npm`).

"Proxies commands" means: `npm run cordova <anything>` === `./node_modules/bin/cordova <anything>`

**Comment by nimaai** [comment]
Hey, thank you so much!

**Comment by nimaai** [comment]
Question: Is it signed and all that? Can users already download the application file and install?

**Comment by eins78** [comment]
No, this just adds output of running `cordova build ios` which creates a project file for Apples proprietary IDE, Xcode. 
This project can then openend and built in  Xcode, for x86 (which runs in a Simulator on Mac) or for arm, which could run on iDevices. 
By default it is self-signed and only runs on your own device. 
If you are a paying developer you can install and test on 100 arbitraty devices, as well as submit to the App Store from where everyone could install.

**Pull request merged**
